### ISSUE TITLE
serve command silently ignores that config file is not found

### ISSUE THREAD

**Issue by cezarguimaraes** [vtex/hyper-cas#2] opened 2020-10-19 16:55 UTC
```console
$ docker run vtexcom/hyper-cas --config /app/hyper-cas.yaml serve
{"level":"info","ts":1603126154.4925814,"caller":"utils/logger.go:37","msg":"Successfully loaded config file.","configPath":"/app/hyper-cas.yaml"}
{"level":"info","ts":1603126154.4965458,"caller":"serve/app.go:91","msg":"hyper-cas API running successfully.","ip":"0.0.0.0","port":2485}
$ docker run vtexcom/hyper-cas --config /app/hyper-cas-no.yaml serve
{"level":"info","ts":1603126172.7463279,"caller":"serve/app.go:91","msg":"hyper-cas API running successfully.","ip":"0.0.0.0","port":2485}
```

**Comment by heynemann** [comment] 2020-10-27 21:36
Good catch! 👍

**Comment by heynemann** [comment] 2020-10-27 21:45
Fixed on 4a0aa9bf496da8ea10c9272f0f2b39e042c82f9b. Waiting for CI to close this.

```
hyper-cas --config qwe.yaml serve
{
"level":"error",
"ts":1603834873.130116,
"caller":"utils/logger.go:49",
"msg":"Specified configuration file does not exist.",
"cfgFile":"qwe.yaml",
"stacktrace":"github.com/vtex/hyper-cas/utils.LogError\n\t/Users/heynemann/dev/vtex/hyper-cas/utils/logger.go:49\ngithub.com/vtex/hyper-cas/cmd.initConfig\n\t/Users/heynemann/dev/vtex/hyper-cas/cmd/root.go:57\ngithub.com/spf13/cobra.(*Command).preRun\n\t/Users/heynemann/dev/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:872\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/heynemann/dev/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:808\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/heynemann/dev/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/heynemann/dev/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\ngithub.com/vtex/hyper-cas/cmd.Execute\n\t/Users/heynemann/dev/vtex/hyper-cas/cmd/root.go:33\nmain.main\n\t/Users/heynemann/dev/vtex/hyper-cas/main.go:27\nruntime.main\n\t/usr/local/Cellar/go/1.14.3/libexec/src/runtime/proc.go:203"
}
exit status 1
```

In case the file exists:

```
hyper-cas --config hyper-cas.yaml serve
{"level":"info","ts":1603835072.826987,"caller":"utils/logger.go:37","msg":"Successfully loaded config file.","configPath":"/Users/heynemann/dev/vtex/hyper-cas/hyper-cas.yaml"}
{"level":"info","ts":1603835072.8281221,"caller":"serve/app.go:91","msg":"hyper-cas API running successfully.","ip":"0.0.0.0","port":2485}
```

**Comment by heynemann** [comment] 2020-10-28 12:29
Hey @cezarguimaraes can you confirm it is working as intended now?

**Comment by cezarguimaraes** [comment] 2020-10-28 18:38
Yep, it's good now @heynemann, thanks!

Though, it seems the CI job failed for some reason: https://travis-ci.org/github/vtex/hyper-cas/jobs/739672032

**Comment by heynemann** [comment] 2020-10-28 18:52
Not really, the build for my commit is this one https://travis-ci.org/github/vtex/hyper-cas/builds/739437069

The other one was cancelled, probably due to a new change in place. I'm closing this issue, then! Thanks for the feedback!

**Closed by heynemann** 2020-10-28 18:52 UTC
